poker-server/poker_server/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('tables/', include('tables.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

poker-server/tables/urls.py
from django.urls import path

from . import views

app_name = 'tables'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:table_id>/', views.detail, name='detail'),
    path('<int:table_id>/play', views.play, name='play'),
    path('<int:table_id>/state', views.state, name='state'),
    path('<int:table_id>/play/reset', views.method_reset, name='method_reset'),
]

poker-server/users/urls.py
from django.urls import include, path

from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('<int:user_id>/info', views.info, name='info'),
]

poker-server/tables/models.py
from django.db import models
from django.contrib.auth.models import User

class Table(models.Model):
    owner = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=128)
    creation_date = models.DateTimeField('date created', auto_now_add=True)

    def __str__(self):
        return f'{self.name} (owner {self.owner})'

class TableState(models.Model):
    table = models.ForeignKey(Table, null=True, on_delete=models.SET_NULL)
    data = models.TextField()

poker-server/tables/forms.py
from django import forms
from .models import Table

class NewTableForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ('name',)

poker-server/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

poker-server/tables/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseForbidden, HttpResponseBadRequest
from .forms import NewTableForm
from .models import TableState
from .models import Table
import json

import poker_core_py

def latest_state(table_id):
    states = TableState.objects.filter(table_id=table_id).order_by('-id')[:1]
    if len(states):
        return states[0].data
    state_data = poker_core_py.new_game_state()
    # print('made new state ------- ')
    # print(state_data)
    state = TableState(table=Table.objects.get(pk=table_id), data=state_data)
    state.save()
    return state.data

def save_state(table, state_data):
    state = TableState(table=table, data=state_data)
    state.save()

@login_required
def index(request):
    if request.method == 'POST':
        form = NewTableForm(request.POST)
        if form.is_valid():
            table = form.save(commit=False)
            table.owner = request.user
            table.save()
            return redirect('tables:detail', table.id)
    latest_tables = Table.objects.order_by('-creation_date')[:10]
    context = {'latest_tables': latest_tables, 'new_table_form': NewTableForm()}
    return render(request, 'tables/index.html', context)

@login_required
def detail(request, table_id):
    table = get_object_or_404(Table, pk=table_id)
    if request.method != 'POST':
        user_is_owner = request.user.id == table.owner.id
        return render(
            request,
            'tables/detail.html',
            {'table': table, 'user_is_owner': user_is_owner})
    if 'join' in request.POST:
        user_id = request.user.id
        table_id = table.id
        stack = 1000
        state = latest_state(table_id)
        try:
            new_state = poker_core_py.seat_player(state, user_id, stack)
        except ValueError as e:
            if str(e) == 'PlayerAlreadySeated':
                return redirect('tables:play', table_id)
        new_state2 = poker_core_py.tick_state(new_state)
        save_state(table, new_state2)
        return redirect('tables:play', table_id)
    elif 'delete' in request.POST:
        table = get_object_or_404(Table, pk=table_id)
        user = request.user
        if request.method != 'POST':
            return HttpResponseNotAllowed(['POST'])
        if table.owner.id != user.id:
            return HttpResponseForbidden()
        table.delete()
        return redirect('tables:index')


@login_required
def play(request, table_id):
    table = get_object_or_404(Table, pk=table_id)
    user = request.user
    # TODO: return page showing table and loading WASM that polls for state updates
    return render(
        request,
        'tables/play.html',
        {
            'table': table,
            'user': user,
        }
    )

def state_since(request, table_id, seq):
    table = get_object_or_404(Table, pk=table_id)
    # TODO: ensure user is seated at table
    user = request.user
    state = latest_state(table.id)
    changes = poker_core_py.state_changes_since(state, seq, user.id)
    return HttpResponse(changes)

def state_action(request, table_id, action, last_seq):
    table = get_object_or_404(Table, pk=table_id)
    # TODO: ensure user is seated at table
    user = request.user
    state = latest_state(table.id)
    new_state = poker_core_py.player_action(state, user.id, action)
    save_state(table, new_state)
    new_state2 = poker_core_py.tick_state(new_state)
    save_state(table, new_state2)
    changes = state_since(request, table_id, last_seq)
    return HttpResponse(changes)

@login_required
def state(request, table_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    obj = json.loads(request.body.decode(request.encoding or 'utf-8'))
    if 'action' in obj and 'since' in obj:
        return state_action(request, table_id, obj['action'], obj['since'])
    elif 'since' in obj:
        return state_since(request, table_id, obj['since'])
    return HttpResponseBadRequest()

@login_required
def method_reset(request, table_id):
    # TODO: ensure user is seated at table
    # TODO: ensure user is admin of table? in future this code should be removed, so maybe not important
    table = get_object_or_404(Table, pk=table_id)
    state = poker_core_py.devonly_reset_state(latest_state(table_id))
    save_state(table, state)
    return redirect('tables:play', table.id)

poker-server/users/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.save()
            pw = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=pw)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def info(request, user_id):
    user = User.objects.filter(id=user_id).values('id', 'username').first()
    return HttpResponse(json.dumps(user), content_type='application/json')

poker-server/tables/templates/tables/detail.html
{% extends 'base.html' %}
{% block content %}
<p>{{ table }}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" name="join">Join table</button>
    {% if user_is_owner %}
    <button type="submit" name="delete">Delete table</button>
    {% endif %}
</form>
{% endblock %}

poker-server/tables/templates/tables/index.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
<h2>Create new table</h2>
{%csrf_token%}
{{new_table_form}}
<button type="submit" name="create">Create</button>
</form>
<h2>Latest tables</h2>
{% if latest_tables %}
<ul>
    {% for table in latest_tables %}
    <li><a href="{% url 'tables:detail' table.id %}">{{ table.name }}</a> ({{table.owner}})</li>
    {% endfor %}
</ul>
{% else %}
<p>No tables, sorry.</p>
{% endif %}
{% endblock %}

poker-server/tables/templates/tables/play.html
{% extends 'base.html' %}
{% block content %}
<p>{{ table }}</p>
<div id='table_container'>
</div>
<div id="action-buttons">
</div>
<div>
    <a href="{% url 'tables:method_reset' table.id %}">Reset game</a>
</div>
<div id="logs"></div>
<pre><span id="state"></span></pre>

{% load static %}
<link rel="stylesheet" href="{% static 'table.css' %}"></style>
<script type=module>
    import * as vars from "{% static 'table_vars.js' %}";
    import * as table from "{% static 'table.js' %}";
    import * as animate from "{% static 'animate.js' %}";
    import init, {
        redraw,
        onclick_fold,
        onclick_check,
        onclick_call,
        onclick_bet,
        onclick_raise,
        onchange_raise,
        save_player_info,
        get_last_seq_num,
        //onclick_bet,
    } from '/static/poker_client.js'
    window.onclick_fold = onclick_fold;
    window.onclick_check = onclick_check;
    window.onclick_call = onclick_call;
    window.onclick_bet = onclick_bet;
    window.onclick_raise = onclick_raise;
    window.onchange_raise = onchange_raise;
    window.send_action = send_action;
    window.send_player_info_request = send_player_info_request;
    window.self_player_id = self_player_id;
    window.ani_redraw_pocket = ani_redraw_pocket;
    window.ani_deal_card_pocket = ani_deal_card_pocket;
    window.ani_deal_card_community = ani_deal_card_community;
    window.ani_reveal_cards = ani_reveal_cards;
    window.ani_clear_community = ani_clear_community;
    window.ani_clear_bets = ani_clear_bets;
    window.ani_clear_pot = ani_clear_pot;
    window.ani_make_bet = ani_make_bet;
    window.ani_collect_pot = ani_collect_pot;
    window.ani_push_winnings = ani_push_winnings;
    window.ani_next_to_act = ani_next_to_act;
    window.animate_next = animate.animate_next;
    let REDRAW_TIMEOUT_ID = 0;
    const WAITING_PLAYER_INFO_REQS = new Set();
    async function run() {
        await init();
        // To call any wasm funcs right after init, do so here.
        redraw_timeout();
        table.initialize_table();
    }
    run();

    function ani_redraw_pocket(seat, name, stack) {
        animate.ANIMATION_QUEUE.push(new animate.RedrawPocketAni(seat, name, stack));
    }

    function ani_deal_card_pocket(seat, card_n, card) {
        animate.ANIMATION_QUEUE.push(new animate.DealCardPocketAni(seat, card_n, card));
    }

    function ani_deal_card_community(card_n, card) {
        animate.ANIMATION_QUEUE.push(new animate.DealCardCommunityAni(card_n, card));
    }

    function ani_reveal_cards(seat_idx, card0, card1) {
        animate.ANIMATION_QUEUE.push(new animate.RevealCardsAni(seat_idx, card0, card1));
    }

    function ani_clear_community() {
        animate.ANIMATION_QUEUE.push(new animate.ClearCommunityAni());
    }

    function ani_clear_bets() {
        animate.ANIMATION_QUEUE.push(new animate.ClearBetsAni());
    }

    function ani_clear_pot() {
        animate.ANIMATION_QUEUE.push(new animate.ClearPotAni());
    }

    function ani_make_bet(seat, stack, wager) {
        animate.ANIMATION_QUEUE.push(new animate.MakeBetAni(seat, stack, wager));
    }

    function ani_collect_pot(pots) {
        animate.ANIMATION_QUEUE.push(new animate.CollectPotAni(pots));
    }

    function ani_push_winnings(seats, winnings) {
        animate.ANIMATION_QUEUE.push(new animate.PushWinningsAni(seats, winnings));
    }

    function ani_next_to_act(seat) {
        animate.ANIMATION_QUEUE.push(new animate.NextToActAni(seat));
    }

    function self_player_id() {
        return {{user.id}};
    }
    function redraw_timeout() {
        let url = "{% url 'tables:state' table.id %}";
        let req = new XMLHttpRequest();
        req.open("POST", url);
        req.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        req.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
        req.send(JSON.stringify({"since": get_last_seq_num()}));
        req.onload = function() {
            if (req.status != 200) {
                alert(`Error ${req.status}: ${req.statusText}`)
                return;
            }
            let wait_time = redraw(req.response);
            REDRAW_TIMEOUT_ID = setTimeout(redraw_timeout, wait_time * 1000);
        };
        req.timeout = 900;
    }

    function send_action(last_seq, opaque_action) {
        let url = "{% url 'tables:state' table.id %}";
        let req = new XMLHttpRequest();
        req.open("POST", url);
        req.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        req.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
        req.send(JSON.stringify({'since': last_seq, 'action': opaque_action}));
        req.onload = function() {
            //alert(`${req}`);
            clearTimeout(REDRAW_TIMEOUT_ID);
            let wait_time = redraw(req.response);
            REDRAW_TIMEOUT_ID = setTimeout(redraw_timeout, wait_time * 1000);
        };
        req.timeout = 900;
    }

    function send_player_info_request(player_id) {
        if (WAITING_PLAYER_INFO_REQS.has(player_id)) {
            return;
        } else {
            WAITING_PLAYER_INFO_REQS.add(player_id);
        }
        let url = `/users/${player_id}/info`;
        let req = new XMLHttpRequest();
        req.open("GET", url);
        req.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        req.send();
        req.onload = function() {
            save_player_info(req.response);
        }
        req.ontimeout = function() {
            WAITING_PLAYER_INFO_REQS.delete(player_id);
        }
        req.onloadend = function() {
            WAITING_PLAYER_INFO_REQS.delete(player_id);
        }
        req.timeout = 900;
    }
</script>
{% endblock %}

poker-server/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {% block head %}
  <link rel="stylesheet" href="{% static 'mvp.css' %}" />
  <title>{% block title %}Cooker Poker{% endblock %}</title>
  {% endblock head %}
</head>
<body>
<header>
  <nav>
    <a href='/'><img src="{% static 'logo.png' %}" width=200 alt=logo /></a>
    <ul>
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'tables:index' %}">Tables</a></li>
      {% if not user.is_authenticated %}
      <li><a href="{% url 'users:login' %}">Login</a></li>
      {% else %}
      <li><a href="{% url 'users:logout' %}">Logout</a></li>
      {% endif %}
    </ul>
  </nav>
</header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

poker-server/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
  <p>Hi {{ user.username }}!</p>
{% else %}
  <p>You are not logged in</p>
{% endif %}
Go to <a href="{% url 'tables:index' %}">tables</a>

<div id='table_container'>
</div>

<style>
</style>

{% load static %}
<script>
</script>
<script src="{% static 'animate.js' %}"></script>
{% endblock %}

poker-server/users/templates/users/register.html
{% extends 'base.html' %}
{% block title %}Create an account{% endblock %}
{% block content %}
<h1>Create an account</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create</button>
</form>
{% endblock %}